server:
  port: 8000
  
spring:
  cloud:
    config:
      uri: http://localhost:8765/  
  zipkin:
    base-url: http://localhost:9411/
  main:    allow-bean-definition-overriding: true
    
      
  h2:    console:      enabled: true
      
  jpa:    show-sql: true