server:
  port: 0
  
  
spring:
  application:
    name: spring-end
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo_bcrypt
    username: root
    password: pass@word1  
    initialization-mode: always
  
       
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    