server:
  port: 9999
  
spring:
  cloud:
    config:
      uri: http://localhost:8765/
  
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints: 
    web: 
      exposure: 
        include: hystrix.stream

      
